include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  errors:
    todo: ignore
  exclude:
    - "**/*.config.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.g.dart"
    - "**/*.i69n.dart"

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
    camel_case_types: true
    omit_local_variable_types: true
    unnecessary_new: true

dart_code_metrics:
  metrics-exclude:
    - test/**
  rules:
    # Common
    - newline-before-return
    - prefer-first
    - prefer-last
    # Flutter
    - always-remove-listener
    - avoid-unnecessary-setstate
