targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true # In order to serialize nested lists of freezed objects
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true