name: int20h_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^3.2.1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  flutter_screenutil: ^5.1.0
  dartz: ^0.10.1
  dio: ^4.0.4
  retrofit: ^3.0.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  flutter_slider_drawer: ^2.0.0
  flutter_chat_ui: ^1.5.4
  dialog_flowtter: ^0.3.3
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  progress_indicators: ^1.0.0
  url_launcher: ^6.0.18
  rive: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.9.1

  build_runner: ^2.1.7
  auto_route_generator: ^3.2.1
  injectable_generator: ^1.5.3
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4
  freezed: ^1.1.1

  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/dialog_flow_auth.json
    - assets/ai.riv
    - assets/ai-2.riv

flutter_icons:
  image_path: assets/logo/AppStore.png
  ios: true
  android: true
  remove_alpha_ios: true
  adaptive_icon_background: assets/logo/android-background.png
  adaptive_icon_foreground: assets/logo/android-foreground.png
